# Generated by Django 4.0.4 on 2022-07-01 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=1024)),
                ('bug_description', models.TextField(blank=True, max_length=2048)),
                ('bug_status', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done')], max_length=10)),
                ('bug_severity', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('LAZY', 'Lazy')], max_length=10)),
                ('bug_assignees', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True, max_length=1500)),
                ('project_technologies_used', models.TextField(blank=True, max_length=1000)),
                ('project_status', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, max_length=2048)),
                ('bug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bug')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
